- name: conf dir
  file:
    path: "{{ mgo_user_dir }}"
    state: directory

- name: standard conf
  template:
    src: muttrc
    dest: "{{ mgo_user_dir }}/muttrc"

- name: color conf
  copy:
    src: "{{ mgo_colors_file }}"
    dest: "{{ mgo_user_dir }}/colors"

- name: editme conf
  copy:
    src: blank-editme-rc
    dest: "{{ mgo_user_dir }}/editme"
    force: no

- name: custom (user supplied?) conf
  copy:
    dest: "{{ mgo_user_dir }}/customrc"
    content: "{{ lookup('file', mgo_custom_rc_file) }}"

- name: alias file
  file:
    path: "{{ mgo_alias_file }}"
    state: touch
  register: alias_touch
  changed_when: ('diff' in alias_touch) and alias_touch.diff.before.state == 'absent'

- name: root conf
  template:
    src: rootrc
    dest: "{{ mgo_rootrc }}"
    force: "{{ mgo_force_set_rootrc }}"
  when: mgo_try_set_rootrc
