- name: copy terrible oauth hack script
  copy:
    src: mutt_oauth2.py
    dest: "{{ mgo_user_dir }}/mutt_oauth2.py"
    mode: 0755

- name: copy wrapper to make terrible hack usable
  template:
    src: oauth-wrap.sh
    dest: "{{ mgo_user_dir }}/oauth-wrap.sh"
    mode: 0755

- name: copy google hack script
  copy:
    src: google-oauth2-script.py
    dest: "{{ mgo_oauth_refresh_script_path }}"
    mode: 0755
