- name: pkgs
  package:
    name:
      - neomutt
      # maybe?
      - offlineimap
      - msmtp
      # in-mutt utils
      - urlscan
    state: present
  become: yes

- name: lots of hacks depend on these
  package:
    name:
      - jq
    state: present
  become: yes
