- name: conf dirs
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ mgo_msmtp_base_dir }}"

- name: msmtp conf
  template:
    src: msmtprc
    dest: "{{ mgo_msmtp_cfg }}"

- name: msmtp script
  template:
    src: "{{ mgo_msmtp_token_script }}"
    dest: "{{ mgo_msmtp_script_path }}"
    mode: 0755
